openapi: 3.2.0
info:
  title: Ew Receiving API
  version: '1.0'
  description: "Receiving Accounts are accounts that function as local bank accounts. \nThey can be used to collect funds from around the world. You get account details that enable you to collect funds from various platforms such as Amazon, Etsy, etc. \n\nYou can apply Receiving Accounts on LianLian Global's website, and by using Receiving API you could query your Receiving accounts and Receiving transactions detail information.\n\n![Wallet.png](https://stoplight.io/api/v1/projects/cHJqOjEyMDg0Ng/images/ooe1JpNsV1Q)"
servers:
- url: https://test-global-api.lianlianpay-inc.com/gateway/v1/
  description: SANDBOX
- url: https://uk-api.lianlianglobal.com/gateway/v1/
  description: UK PRD
- url: https://us-api.lianlianglobal.com/gateway/v1/
  description: US PRD
tags:
- name: Ew Receiving
paths:
  /ew-receiving/accounts:
    parameters: []
    get:
      summary: Get Receiving Account list
      tags:
      - Ew Receiving
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReceivingAccount'
      operationId: get-receivings-accounts
      description: 'Get list of receiving accounts created by your LianLian Global account.

        '
      requestBody:
        content:
          application/json:
            schema:
              type: string
  /ew-receiving/accounts/{id}:
    parameters:
    - schema:
        type: string
      name: id
      in: path
      required: true
    get:
      summary: Get Receiving Account Info by ID
      tags:
      - Ew Receiving
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceivingAccount'
      operationId: get-receivings-accounts-id
      description: Retrieve the information of the Receiving Account with the matching ID.
components:
  schemas:
    ReceivingAccount:
      type: object
      x-tags:
      - Models
      properties:
        id:
          type: string
          description: Unique ID created by the LianLian Global.
        nickname:
          type: string
          description: Nickname of `ReceivingAccount`
        receiving_account_info:
          $ref: ./CommonModel.json#/components/schemas/VbaBankInfo
        shops:
          type: array
          items:
            $ref: ./CommonModel.json#/components/schemas/UserShop
x-stoplight:
  id: drmdm24yuutvg
