definitions:
  RecevingAccount:
    title: CNY Virtual Account
    type: object
    description: Lianlian Pay CNY virtual account information
    x-tags:
      - Models
    properties:
      virtualAcctId:
        type: string
        description: unique Virtual Account ID from client
        maxLength: 64
      accountName:
        type: string
        description: receiving account name
        maxLength: 72
      accountNo:
        type: string
        description: receiving account number
        maxLength: 72
      bankBranchName:
        type: string
        description: receiving account bank branch name
        maxLength: 256
      bankName:
        type: string
        description: 'receiving account bank name, mandatory for corporate payer'
        maxLength: 128
      cnapsBranchId:
        type: string
        description: CNAPS code
        maxLength: 12
      bankDistrict:
        type: string
        description: Receiving account bank branch address
        maxLength: 200
  FundingTrans:
    title: FundingTrans
    type: object
    description: Funding transication record object in Lianlian Pay's system
    x-tags:
      - Models
    properties:
      fundingId:
        type: string
        description: Funding transaction id in Lianlian Pay's system
        maxLength: 32
      virtualAcctId:
        type: string
        maxLength: 64
        description: unique Virtual Account ID from client
      accountNo:
        type: string
        description: receiving account number
        maxLength: 72
      payerName:
        type: string
        description: Payer name
        maxLength: 128
      payerBankAccount:
        type: string
        description: payer bank account number
        maxLength: 72
      payerBankName:
        type: string
        description: payer bank name
        maxLength: 72
      amount:
        type: string
        description: amount in CNY
        maxLength: 24
      createTime:
        type: string
        description: |-
          Funding transication time
          UTC+0
        maxLength: 64
      rfb:
        type: string
        description: rfb
        maxLength: 40
    required:
      - fundingId
      - accountNo
      - payerName
      - payerBankAccount
      - payerBankName
      - amount
      - createTime
  CNYReFundTrans:
    title: CNYReFundTrans
    type: object
    description: CNY Refunding transication record object in Lianlian Pay's system
    x-tags:
      - Models
    properties:
      refundingId:
        type: string
        description: Unique refunding request id
        maxLength: 32
      virtualAcctId:
        type: string
        description: unique Virtual Account ID from client
        maxLength: 64
      amount:
        type: string
        description: requested refunding amount
        maxLength: 24
      bankAccountType:
        type: string
        description: |-
          Beneficiary account type, one of:

          |value|description|
          |------|------------|
          |INDIVIDUAL|Individual account|
          |CORPORATE|Corporate account|
        enum:
          - INDIVIDUAL
          - CORPORATE
      bankName:
        type: string
        description: beneficiary bank name
        maxLength: 128
      bankBranchName:
        type: string
        description: Bank branch name
        maxLength: 256
      cnapsBranchId:
        type: string
        description: |-
          CNAPS code
          Mandatory is `bankAccountType = CORPORATE`
        maxLength: 12
      bankCode:
        type: string
        description: 'Bank Code defined by Lianlian Pay, mandatory if `bankAccountType = CORPORATE`. Please refer to appendix Bank List'
        maxLength: 8
        minLength: 8
      payeeName:
        type: string
        description: beneficiary account name
        maxLength: 72
      payeeBankAccount:
        type: string
        description: beneficiary account number
        maxLength: 72
      rfb:
        type: string
        description: rfb
        maxLength: 40
      createTime:
        type: string
        format: date-time
        description: Refunding create time
      modifyTime:
        type: string
        description: Refund modify time
        format: date-time
      status:
        type: string
        description: |-
          refunding status, one of:

          | value |description|
          |------|------------|
          |INIT| Init |
          |SUCCESS|Success|
          |PROCESSING|Processing |
          |FAILED|failed|
          |HEDGED|refund failed after success|
        enum:
          - PROCESSING
          - SUCCESS
          - FAILED
          - HEDGED
      failReason:
        type: string
        description: Refund failure reason
        maxLength: 128
    required:
      - refundingId
      - amount
      - payeeName
      - payeeBankAccount
      - createTime
      - status
  CNYPaymentTrans:
    title: CNYPaymentTrans
    type: object
    description: CNY Payment transication record object in Lianlian Pay's system
    x-tags:
      - Models
    properties:
      paymentId:
        type: string
        description: Unique refunding request id
        maxLength: 32
      virtualAcctId:
        type: string
        description: unique Virtual Account ID from client
        maxLength: 64
      amount:
        type: string
        description: requested refunding amount
        maxLength: 24
      bankAccountType:
        type: string
        description: |-
          Beneficiary account type, one of:

          |value|description|
          |------|------------|
          |INDIVIDUAL|Individual account|
          |CORPORATE|Corporate account|
        enum:
          - INDIVIDUAL
          - CORPORATE
      bankName:
        type: string
        description: beneficiary bank name
        maxLength: 128
      bankBranchName:
        type: string
        description: Bank branch name
        maxLength: 256
      cnapsBranchId:
        type: string
        description: |-
          CNAPS code
          Mandatory is `bankAccountType = CORPORATE`
        maxLength: 12
      bankCode:
        type: string
        description: 'Bank Code defined by Lianlian Pay, mandatory if `bankAccountType = CORPORATE`. Please refer to appendix Bank List'
        maxLength: 8
        minLength: 8
      payeeName:
        type: string
        description: beneficiary account name
        maxLength: 72
      payeeBankAccount:
        type: string
        description: beneficiary account number
        maxLength: 72
      rfb:
        type: string
        description: rfb
        maxLength: 40
      createTime:
        type: string
        format: date-time
        description: Refunding create time
      modifyTime:
        type: string
        description: Refund modify time
        format: date-time
      status:
        type: string
        description: |-
          refunding status, one of:

          | value |description|
          |------|------------|
          |INIT| Init |
          |SUCCESS|Success|
          |PROCESSING|Processing |
          |FAILED|failed|
          |HEDGED|refund failed after success|
        enum:
          - PROCESSING
          - SUCCESS
          - FAILED
          - HEDGED
      failReason:
        type: string
        description: Refund failure reason
        maxLength: 128
    required:
      - paymentId
      - amount
      - bankAccountType
      - payeeName
      - payeeBankAccount
      - createTime
      - modifyTime
paths:
  /cnyva:
    post:
      summary: Create a CNY Virtual Account
      operationId: post-payers
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RecevingAccount'
        '400':
          description: |-
            Bad Request

            Possible error codes:

            | Code | Description |
            |------|-------------|
            | 020101|Payer audit failure |
            | 020402|billId already exist|
            |020105|Payer rejectd by blacklist|
            | 999995 |Parameter is error. |
          schema:
            type: object
            properties: {}
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties: {}
      description: ''
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              virtualAcctId:
                type: string
                description: unique Virtual Account ID from client
                maxLength: 64
            required:
              - virtualAcctId
          description: ''
      tags:
        - Operations
      consumes:
        - application/json
      produces:
        - application/json
  '/cnyva/{virtualAcctId}':
    parameters:
      - name: virtualAcctId
        in: path
        type: string
        required: true
    get:
      summary: Get CNY VA Information
      tags:
        - Operations
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RecevingAccount'
        '400':
          description: |-
            Bad Request

            Possible error codes:

            | Code | Description |
            |------|-------------|
            | 999995 | \[PARAMETER\] ERROR_MESSAGE |
          schema:
            type: object
            properties: {}
        '404':
          description: Not Found
          schema:
            type: object
            properties: {}
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties: {}
      operationId: get-bills-billid
      description: ''
      parameters: []
      produces:
        - application/json
      consumes:
        - application/json
  '/fundingtrans/{fundingId}':
    parameters:
      - name: fundingId
        in: path
        type: string
        required: true
    get:
      summary: Get Funding Trans by ID
      tags:
        - Operations
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FundingTrans'
        '400':
          description: |-
            Bad Request

            Possible error codes:

            | Code | Description |
            |------|-------------|
            | 999995 | \[PARAMETER\] ERROR_MESSAGE |
          schema:
            type: object
            properties: {}
        '404':
          description: Not Found
          schema:
            type: object
            properties: {}
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties: {}
      operationId: get-fundingid-fundingtrans
      description: Get Funding record by funding ID
      parameters: []
      produces:
        - application/json
      consumes:
        - application/json
  /fundingtrans:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              fundingTrans:
                type: array
                description: Funding Records
                items:
                  $ref: '#/definitions/FundingTrans'
              totalCount:
                type: string
                description: Total count of funding records
              pageNum:
                type: string
                description: 'if nonzero, skip this number of results before returning data. Used with pageSize to provide pagination for large datasets'
              pageSize:
                type: string
                description: 'if nonzero, return no more than this number of results. Used with pageNum to provide pagination for large datasets. Unless otherwise specified, the maximum number of records that can be returned from an API call is 100 records(default to 20 records)'
        '400':
          description: |-
            Bad Request

            Possible error codes:

            | Code | Description |
            |------|-------------|
            | 999995 | \[PARAMETER\] ERROR_MESSAGE |
        '500':
          description: ''
      summary: Get List of Funding Trans
      tags:
        - Operations
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - type: string
          in: query
          name: beginTime
          required: true
          description: 'beginning time of funding created, in format of timestamp and units are seconds'
        - type: string
          in: query
          name: endTime
          required: true
          description: 'ending time of funding created, in format of timestamp and units are seconds'
        - type: string
          in: query
          name: pageNum
          description: 'if nonzero, skip this number of results before returning data. Used with pageSize to provide pagination for large datasets'
        - type: string
          in: query
          name: pageSize
          description: 'if nonzero, return no more than this number of results. Used with pageNum to provide pagination for large datasets. Unless otherwise specified, the maximum number of records that can be returned from an API call is 100 records(default to 20 records)'
        - type: string
          in: query
          name: virtualAcctId
          maxLength: 64
          description: unique Virtual Account ID from client
      description: The scale of the search cannot exceed 7 days
  /paymenttrans:
    post:
      summary: Create CNY Payment Transaction
      operationId: post-paymenttrans
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CNYPaymentTrans'
      description: |-
        Create a single CNY Payment request, results will be noticed via webhook event. Client can also use `Query Refunding Trans` API to retrieve coresponding request results.

        Requested total refudning amount shall no larger than total funding amount.
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              paymentId:
                type: string
                description: Unique payment request id
                maxLength: 32
              virtualAcctId:
                type: string
                description: unique Virtual Account ID from client
                maxLength: 64
              amount:
                type: string
                description: requested refunding amount
                maxLength: 24
              bankAccountType:
                type: string
                description: |-
                  Beneficiary account type, one of:

                  |value|description|
                  |------|------------|
                  |INDIVIDUAL|Individual account|
                  |CORPORATE|Corporate account|
                enum:
                  - INDIVIDUAL
                  - CORPORATE
              bankName:
                type: string
                description: beneficiary bank name
                maxLength: 128
              bankBranchName:
                type: string
                description: Bank branch name
                maxLength: 256
              bankCode:
                type: string
                description: 'Bank Code defined by Lianlian Pay, mandatory if `bankAccountType = CORPORATE`. Please refer to appendix Bank List'
                maxLength: 8
                minLength: 8
              cnapsBranchId:
                type: string
                description: |-
                  CNAPS code
                  Mandatory is `bankAccountType = CORPORATE`
                maxLength: 12
              payeeName:
                type: string
                description: beneficiary account name
                maxLength: 72
              payeeBankAccount:
                type: string
                description: beneficiary account number
                maxLength: 72
              rfb:
                type: string
                description: rfb
                maxLength: 40
            required:
              - paymentId
              - virtualAcctId
              - amount
              - bankAccountType
              - payeeName
              - payeeBankAccount
          description: ''
      tags:
        - Operations
  '/paymenttrans/{paymentId}':
    parameters:
      - type: string
        name: paymentId
        in: path
        required: true
    get:
      summary: Get CNY Payment Information
      tags:
        - Operations
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CNYPaymentTrans'
      operationId: get-paymenttrans-paymentId
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
host: global-api.lianlianpay.com/
info:
  title: Payer API
  version: '1.0'
  description: ''
swagger: '2.0'
tags:
  - name: Operations
basePath: outbound/card/v1/
