{
    "openapi": "3.1.0",
    "info": {
        "title": "Exchange",
        "version": "1.0",
        "description": "The Conversion resources provide the capability to create transactions that convert from one currency into another. \n\nA LockFX Quote can be used when creating a Conversion transaction within validity period."
    },
    "servers": [
        {
            "url": "https://test-global-api.lianlianpay-inc.com/gateway/v1/",
            "description": "SANDBOX"
        },
        {
            "url": "https://uk-api.lianlianglobal.com/gateway/v1/",
            "description": "UK PRD"
        },
        {
            "url": "https://us-api.lianlianglobal.com/gateway/v1/",
            "description": "US PRD"
        }
    ],
    "paths": {
        "/ew-conversions": {
            "post": {
                "summary": "Create a Conversion",
                "operationId": "post-conversion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Conversion"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                },
                "tags": [
                    "Operations"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "./CommonModel.json#/components/schemas/ConversionRequest"
                            }
                        }
                    }
                },
                "description": "Create a new `Conversion` to be executed. To associate a conversion with a `Payout`, use the Payout API.\nNote: On a conversion, both `buy_currency` and `sell_currency` will be populated, but define only one of either `buy_amount` or `sell_amount`. "
            },
            "parameters": []
        },
        "/ew-conversions/{request_id}": {
            "parameters": [
                {
                    "schema": {
                        "type": "string"
                    },
                    "name": "request_id",
                    "in": "path",
                    "required": true
                }
            ],
            "get": {
                "summary": "Get Conversion by Request_ID",
                "tags": [
                    "Operations"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Conversion"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                },
                "operationId": "get-conversion-conversion_id",
                "parameters": [],
                "description": "Get detail of a `Conversion` transaction."
            }
        }
    },
    "components": {
        "schemas": {
            "Conversion": {
                "title": "Conversion",
                "type": "object",
                "x-tags": [
                    "Models"
                ],
                "description": "",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "unique ID created by the LianLian Global conversion."
                    },
                    "request_id": {
                        "type": "string",
                        "description": "The idempotent value generated by the client must be unique on each request. Conversion requests with the same `request_id` will be rejected. The parameter contains a maximum of 128 characters."
                    },
                    "business_order_id": {
                        "type": "string",
                        "description": "Business Order ID."
                    },
                    "user_id": {
                        "type": "string",
                        "description": "Unique identifier of the User."
                    },
                    "sell_currency": {
                        "type": "string",
                        "description": "Sell currency, the currency that the client sells (in three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format)."
                    },
                    "sell_amount": {
                        "type": "string",
                        "description": "Amount in `sell_currency` that the client sells. Required if `buy_amount` is not specified."
                    },
                    "buy_currency": {
                        "type": "string",
                        "description": "Buy currency, the currency that the client buys (in three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format)."
                    },
                    "buy_amount": {
                        "type": "string",
                        "description": "Amount in `buy_currency` that the client buys. Required if `sell_amount` is not specified. Main currency unit, rounded up to 2 decimal places."
                    },
                    "rate_id": {
                        "type": "string",
                        "description": "The LockFX Quote is used to execute the conversion. Echoes the request’s LockFX Quote, if provided."
                    },
                    "rate": {
                        "type": "string",
                        "description": "The FX Quoterepresents how much of the quote currency is needed for you to get one unit of the base currency."
                    },
                    "base_currency": {
                        "type": "string",
                        "description": "It will be either `sell_currency` or `buy_currency`."
                    },
                    "status": {
                        "type": "string",
                        "description": "Status of the conversion",
                        "enum": [
                            "SETTLED",
                            "CANCELLED",
                            "WAITING_SETTLEMENT"
                        ]
                    },
                    "create_time": {
                        "type": "string",
                        "description": "The object creation time. Measured in milliseconds since the Unix epoch."
                    }
                }
            }
        },
        "requestBodies": {}
    }
}